Added package-module-winget and needed dependency powershell-execution-policy
cfengine/modules pull request #101
Opened 2024-08-30 13:51 UTC by craigcomstock

Ticket: ENT-12127

2024-08-30 13:55 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +      "powershell_execution_policy_set" usebundle => powershell_execution_policy_set("LocalMachine", "Unrestricted"),
@nickanderson I think we talked about making this an opt-in class maybe? I can add a README explaining why it is needed, so that we can install winget in case it is needed to be installed which should only apply to older Windows versions so maybe "OK" if I change this to make the powershell execution policy set depend on `winget_installed` and `winget_module_installed` classes below. But... I think the module may always NOT be installed by default so would still be essentially "required" for this package module to operate properly.

I will be doing some testing on my Windows 10 and other newer server cloud instances now.

2024-08-30 14:13 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +      "powershell_execution_policy_set" usebundle => powershell_execution_policy_set("LocalMachine", "Unrestricted"),
updated.

2024-08-30 15:00 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_no_powershell_execution_changes::
To avoid "negative knowledge" I suppose an opt-in would be better:

```suggestion
    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_allow_powershell_execution_changes::
```

2024-08-30 15:00 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_no_powershell_execution_changes::
@nickanderson opinion? If someone doesn't read the README and the policy they might get errors so maybe a report if these bits need installation by the ps1 scripts but the opt-in class is not defined?

2024-08-30 15:58 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +      "powershell_execution_policy_set" usebundle => powershell_execution_policy_set("LocalMachine", "Unrestricted"),
Thinking about this change some more I wonder if we shouldn't rather sign our scripts: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.4

By default it seems AWS windows instances have LocalMachine set to RemoteSigned.

2024-08-30 18:31 UTC, nickanderson requested changes

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/README
> +package-module-winget
I know that this is a build /module/ but the implementation here is a package /method/

So I would suggest renaming this to package-method-winget.

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/README
> +Note that this module uses both the `winget` command as well as the PowerShell WinGet Client cmdlets as they make it easier to gather software inventory of currently installed packages.
```suggestion
Note that this module uses both the `winget` command as well as the `PowerShell WinGet Client` _cmdlets_ as they make it easier to gather software inventory of currently installed packages.
```

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/README
> +In order for `winget` to be installed and Microsoft.WinGet.Client (the cmdlets module) ps1 scripts must be run which requires PowerShell Execution policy Unrestricted for LocalMachine.
```suggestion
In order for `winget` to be installed and `Microsoft.WinGet.Client` (the cmdlets module) ps1 scripts must be run which requires `PowerShell Execution policy` `Unrestricted` for `LocalMachine`.
```

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/README
> +```
I would prefer the new more explicit (albeit complex style)

```json
{
  "classes": {
    "data:winget_installed_allow_powershell_execution_changes": {
      "class_expressions":  [ "windows::" ],
      "comment": "winget will not function without the ability to execute powershell scripts"
    }
  }
}
```

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/package-module-winget.cf
> +      package_list_version_regex => '.*,"([^"]*)".*';
Would be nice to have some sample output comment stub to easily reference what these look to match against.

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/package-module-winget.cf
> +      package_add_command    => "$(sys.winsysdir)\\WindowsPowerShell\\v1.0\\powershell.exe -Command \"winget install --accept-source-agreements --accept-package-agreements ";
I think this needs to be guarded against until the user has explicitly provided input to accept the agreements.

2024-08-30 18:31 UTC, nickanderson commented on management/package-module-winget/winget-installed.cf
> +      "powershell_execution_policy_set" usebundle => powershell_execution_policy_set("LocalMachine", "Unrestricted"),
I am not sure we should acquire code signing certificates for this. 
Were you thinking of dynamically self signing the script on each host and then relying on that self signature to suffice?

2024-08-30 18:31 UTC, nickanderson commented on cfbs.json
> +    "package-module-winget": {
I think this one should have module input for accepting the license agreements.

2024-08-30 18:59 UTC, nickanderson commented on management/package-module-winget/winget-installed.cf
> +    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_no_powershell_execution_changes::
Yeah, good idea.

2024-08-30 18:59 UTC, nickanderson commented on management/package-module-winget/winget-installed.cf
> +    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_no_powershell_execution_changes::
though, reports only goto console, they dont really come to mission portal sadly.

2024-09-03 17:40 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +    windows.(winget_not_installed|winget_module_not_installed).data:winget_installed_no_powershell_execution_changes::
yeah, I couldn't figure out or think of a way to get these bits into not kept promises that could be seen in policy analyzer/reports.

2024-09-03 17:41 UTC, craigcomstock commented on management/package-module-winget/winget-installed.cf
> +      "powershell_execution_policy_set" usebundle => powershell_execution_policy_set("LocalMachine", "Unrestricted"),
Just thinking about what we should do other than "Unrestricted". I suppose self-signing scripts that we pull from a policy server makes "some sense" but is probably not the right answer. We can likely leave as-is.

2024-09-03 17:41 UTC, craigcomstock commented on management/package-module-winget/README
> +package-module-winget
changed, yes.

2024-09-03 18:59 UTC, nickanderson commented on management/package-method-winget/package-method-winget.cf
> +{
```suggestion
# @brief Verify user acceptance of source and package agreements
# these MUST be agreed to in order for this package method to work properly.
{
```

You can make that comment a brief description bit more in line with style of MPF. It's pretty low value though because the only tooling that uses that is our official docs site.

2024-09-03 18:59 UTC, nickanderson commented on management/package-method-winget/package-method-winget.cf
> +        "${package_method_winget:package_method_winget.accept_source_agreements}");
Sorry, it's not clear to me. Why do you have to look for these in 3 places? 

Why not just `package_method_winget:package_method_winget.accept_source_agreements` and `package_method_winget:package_method_winget.accept_package_agreements`?

2024-09-03 18:59 UTC, nickanderson commented on management/package-method-winget/package-method-winget.cf
> +      scope => "namespace";
So accept in any case y, ye, yes

2024-09-03 19:13 UTC, craigcomstock commented on management/package-method-winget/package-method-winget.cf
> +        "${package_method_winget:package_method_winget.accept_source_agreements}");
just two different namespaces: data (for host/group data) and bundle for inputs.

Ideally we should be registering these variables/classes with meta data that Mission Portal can scrape to auto-populate possible tunables in the UI but :cloud: (dreaming).

2024-09-04 17:59 UTC, nickanderson requested changes
I think the module input hasn't yet been updated to target the data namespace.
Minor suggestion of style for README mentioning variables (use verbatim)

Overall seems to make sense to me.

2024-09-04 17:59 UTC, nickanderson commented on management/package-method-winget/README.md
> +- data:package_method_winget.accept_package_agreements
Is this documentation stale? I thought you circled into a single hinge for each of these but I see inputs targets the `package_method_winget` namespace instead of data as shown here.

Also, suggest verbatim for these.

```suggestion
- `data:package_method_winget.accept_source_agreements`
- `data:package_method_winget.accept_package_agreements`
```

2024-09-04 17:59 UTC, nickanderson commented on management/package-method-winget/README.md
> +- data:package_method_winget.accept_package_agreements
Reading a bit further, it seems like maybe its the module input that hasn't been updated yet.

2024-09-04 17:59 UTC, nickanderson commented on cfbs.json
> +        },
Didn't you move these to the data namespace?

2024-09-04 18:42 UTC, craigcomstock commented on cfbs.json
> +        },
yes, fixed. :+1:

2024-09-04 18:51 UTC, craigcomstock commented on management/package-method-winget/README.md
> +- data:package_method_winget.accept_package_agreements
fixed

2024-09-04 20:36 UTC, nickanderson commented on cfbs.json
> +      "input": [
I would explicitly target the `data` namespace here but that's pretty minor.

2024-09-04 20:43 UTC, nickanderson commented
Actually I just ran a test with cfbs, and it seems that namespace is required for input.

```
$ cfbs build
Error in cfbs.json for module 'lynis': The "namespace" field is required in module input elements
WARNING: At least one error encountered while validating your cfbs.json file.
Please see the error messages above and apply fixes accordingly.
If not fixed, these errors will cause your project to not build in future cfbs versions.

Modules:
001 masterfiles @ d5d5c61942a97ec5e3fd35478e590c5943db5ac5 (Downloaded)
002 lynis       @ 4db6d515c45873a9f3fa7ce78ece593027464b64 (Downloaded)

Steps:
001 masterfiles : run 'EXPLICIT_VERSION=3.24.0 EXPLICIT_RELEASE=1 ./prepare.sh -y'
001 masterfiles : copy './' 'masterfiles/'
002 lynis       : copy 'policy/main.cf' 'masterfiles/services/lynis/main.cf'
002 lynis       : json 'cfbs/def.json' 'masterfiles/def.json'
002 lynis       : input './input.json' 'masterfiles/def.json'

Generating tarball...

Build complete, ready to deploy 🐿
 -> Directory: out/masterfiles
 -> Tarball:   out/masterfiles.tgz

To install on this machine: sudo cfbs install
To deploy on remote hub(s): cf-remote deploy

```

snippet of my cfbs.json whre I removed the namespace key for the input step for setting tar_url.

```
      "input": [
        {
          "type": "string",
          "namespace": "lynis",
          "bundle": "globals",
          "variable": "version",
          "label": "Lynis version",
          "question": "What version of Lynis should be used?",
          "default": "3.1.1"
        },
        {
          "type": "string",
          "bundle": "globals",
          "variable": "tar_url",
          "label": "Tarball url",
          "question": "Where should clients download lynis from (http/https)",
          "default": "https://downloads.cisofy.com/lynis/lynis-$(version).tar.gz",
          "comment": "Some may want to self host the tarball within their own infrastructure. This provides an easy way to do that. Note, the archive should be named for the version of Lynis selected."
        },

```

2024-09-04 20:44 UTC, nickanderson requested changes
I think you must set namespace for module input.

2024-09-04 20:54 UTC, craigcomstock commented
I didn't have to with cfbs 4.2.1 which is odd since we are both using that version. I suppose you are using a build index module and I am using a repo#commit. Maybe that's the diff.

2024-09-04 21:04 UTC, nickanderson approved these changes

2024-09-04 21:19 UTC, merged