add newer class for purging policies
cfengine/modules pull request #103
Opened 2024-09-19 15:05 UTC by craigcomstock

Running on 3.24.x I get the following report/warning

```
R: `cfengine_internal_purge_policies` no longer has any effect. Please use `cfengine_internal_purge_policies_disabled` instead, to choose where you want to disable purging or remove the class completely if you want purging enabled everywhere (the new default in 3.18+).
```

I figured we should add both? So that this demo module works on older versions but the note mentions 3.18+ so maybe we can just remove instead).

2024-09-19 17:00 UTC, nickanderson requested changes
I think we should simply delete both.

2024-09-19 17:00 UTC, nickanderson commented on management/demo/def.json
> +        "cfengine_internal_purge_policies_disabled": ["any"],
```suggestion
```

The class `cfengine_internal_purge_policies` would enable that feature on older versions of the MPF. When this feature was enabled files inside of /var/cfengine/inputs that did not exist on the servers /var/cfengine/masterfiles would be removed from the client, in effect a sync behavior instead of the default to just copy files on top if changes were made, leaving extra files alone.

That default changed and so now that behavior is the default. If you previously had  `cfengine_internal_purge_policies`  defined then today you should simply disable the definition of that class to keep that sync behavior. Alternatively, if you desire the old behavior where extra files were not cleaned up then you would instead define `cfengine_internal_purge_policies_disabled`.

Since, this was enabling that feature which is now the default, I think that both of these should just be removed.

2024-09-19 17:56 UTC, nickanderson requested changes

2024-09-19 17:56 UTC, nickanderson commented on management/demo/def.json
> +        "cfengine_internal_purge_policies_disabled": ["any"],
After thinking about this for a moment another option would be to adjust `cfengine_internal_purge_policies` to target `cfengine_3_18` if the desire is to keep that behavior for older clients that may still be using this. Otherwise, still best to remove both i think.

2024-09-30 20:48 UTC, craigcomstock commented on management/demo/def.json
> +        "cfengine_internal_purge_policies_disabled": ["any"],
agreed. I didn't read things quite right. Will adjust.

2024-09-30 20:52 UTC, craigcomstock commented
closed in preference for more appropriate change: https://github.com/cfengine/modules/pull/105

2024-09-30 20:52 UTC, closed without merging