ENT-7423: Tweaked iptables README
cfengine/modules pull request #19
Opened 2021-09-23 16:14 UTC by KotzaBoss

Ticket: ENT-7423

2021-09-27 11:50 UTC, olehermanse requested changes
Please stop using `...` in the examples. Write short examples that are runnable instead.

2021-09-27 11:50 UTC, olehermanse commented on promise_types/iptables/README.md
> +      ...
Please make this a valid runnable example, no `...`.

2021-09-28 09:46 UTC, KotzaBoss commented
Example validity tested by running `cf-promises` on them

2021-09-28 13:06 UTC, olehermanse requested changes
Looks good, just some smaller questions on the later examples.

2021-09-28 13:06 UTC, olehermanse commented on promise_types/iptables/README.md
> +    "cfengine_control" data => '{
```suggestion
    "rules" data => '{
```

2021-09-28 13:06 UTC, olehermanse commented on promise_types/iptables/README.md
> +bundle common IptablesKnowledge
```suggestion
bundle common allow_cfengine_and_ssh
```

2021-09-29 13:10 UTC, KotzaBoss commented on promise_types/iptables/README.md
> +        table => ${cfe[rule1][table]},
This is an error during refactoring. Fixed by renaming it to `rules` which is a local variable to save writting the whole `IptablesCFEngine.rules`

2021-09-29 13:13 UTC, KotzaBoss commented on promise_types/iptables/README.md
> +bundle common IptablesCFEngine
The naming is mediocre your suggestion is better for the example. I have it as a separate bundle simply to separate the rules from the "use" of them. It may be smth unique to me that i like to, fairly aggressively, separate this kind of "static" data from its use. Moving it into a variable in the bundle is trivial and can let the user decide their policy structure.
Should i move it to the bundle?

2021-09-29 13:34 UTC, KotzaBoss commented on promise_types/iptables/README.md
> +        table => ${cfe[rule1][table]},
`cf-promises` did not complain interestingly. Is this something to be expected?

2021-10-01 14:10 UTC, olehermanse commented on promise_types/iptables/README.md
> +        table => ${cfe[rule1][table]},
Yes, CFEngine is a dynamic language and `cf-promises` is more of a syntax checker. This is valid syntax, and `cf-promises` cannot know whether that variable will exist or not.

2021-10-01 14:20 UTC, olehermanse commented on promise_types/iptables/README.md
> +bundle common AllowIncomingCFEngine
Since we typically use underscores for names everywhere, I'd suggest doing it here as well, so `allow_incoming_cfengine`. (More readable IMO).

Not a big deal, feel free to submit it as a small follow up PR.

2021-10-01 14:21 UTC, olehermanse approved these changes

2021-10-01 14:21 UTC, merged