Fix (invert) logic when downloading files over 512kb
cfengine/modules pull request #47
Opened 2022-08-03 09:40 UTC by Lex-2008

Also fix a typo

Ticket: ENT-9047

2022-08-03 10:40 UTC, vpodzime reviewed
Please use `KiB` as the unit in the commit message and mention it's a fix in the *http* promise type.

2022-08-03 10:41 UTC, vpodzime commented
And thanks for the fix, of course!

2022-08-03 10:42 UTC, Lex-2008 commented
All thanks go to reporter in the support ticket! (I don't know if we can disclose their name in a public repo?)

2022-08-03 11:54 UTC, olehermanse commented
> All thanks go to reporter in the support ticket! (I don't know if we can disclose their name in a public repo?)

@Lex-2008 definitely not :) (Unless you ask for permission, of course)

2022-10-10 13:26 UTC, nickanderson commented
I pushed a change to change the commit per comment from @vpodzime .

Is this ready to go in now?

Side note: Does this module *require* python 3?

2022-10-10 14:05 UTC, vpodzime reviewed
The commit now has many more changes. Ideally, they should gop into separate commits or else the commit message should be amended to mention them.

2022-10-10 16:38 UTC, nickanderson commented
> The commit now has many more changes. Ideally, they should gop into separate commits or else the commit message should be amended to mention them.
OK.

@vpodzime I looked up the last comment from the original author of the change:

```
Change `__init__`'s signature so that the `HTTPPromiseModule` can be extended.
Create a new `target_fh` context that simplifies the logic for if target is set or not.
`target_fh` will write to a temp file (this is important so that you don't run into the condition where a client pulls files from the hub while a file is still being written).
`target_fh` creates the path to the target, if it doesn't exist.
`evaluate_promise` returns KEPT if there was not any changes to the file, otherwise the promise is REPAIRED. (before it was always repaired)
```

I used that to formulate a new commit message.

2022-10-11 20:11 UTC, craigcomstock commented on promise-types/http/http_promise_type.py
> +            yield open(os.devnull, "wb")
What is the purpose of returning `os.devnull` aka `/dev/null` here? If I read the code correctly the request would occur, the contents read and written to `/dev/null` with the result would always be `KEPT`. I suppose this is to do something like API requests where you don't care about the result other than response code?

If so, I think a comment here would be helpful to explain and possibly explain in docs the option to provide no `file` attribute as well.

2022-10-11 20:12 UTC, craigcomstock requested changes
Looks like this PR addresses two TODOs in the README that should be updated as well as add a note to the README about skipping the "file" attribute as a viable option for some particular purpose.

At least fix the spelling in README `s/Lenght/Length/`

```
[ ] progress reporting if response Content-Lenght is big
[ ] GET requests should not overwrite data if it is the same
```

2022-10-11 20:46 UTC, craigcomstock commented on promise-types/http/http_promise_type.py
> +                if not (200 <= url_req.status <= 300):
Interestingly, 300 code (rarely used), means "multiple choices" for redirect so it seems this should be `< 300` instead of `<= 300`.
```suggestion
                if not (200 <= url_req.status < 300):
```

2022-10-11 20:50 UTC, craigcomstock commented on promise-types/http/http_promise_type.py
> +            yield open(os.devnull, "wb")
@nickanderson I would suggest an addition to the README, maybe near Result Classes of:

```
Note: if no `file` attribute is provided the request will be sent to `/dev/null`. This is useful for something like a REST API endpoint where all you care about is an OK response (http code between 200 and 300) that results in the promise being `KEPT`
```

2022-10-11 20:56 UTC, nickanderson commented on promise-types/http/http_promise_type.py
> +                if not (200 <= url_req.status <= 300):
Added in separate commit.

2022-10-11 20:57 UTC, craigcomstock approved these changes
🍕 !!!

2022-10-11 21:02 UTC, nickanderson commented
Will leave merging for someone else in case there are more complaints. Added corollary PR to update build index.

2022-10-12 08:53 UTC, olehermanse approved these changes
Looks good to me :)

2022-10-12 08:53 UTC, merged

2022-10-13 12:58 UTC, nickanderson commented
Thanks for the contribution @bim9262 !

2022-10-14 16:50 UTC, bim9262 commented
You're welcome!