RFC: Ansible INI module
cfengine/modules pull request #88
Opened 2024-01-10 14:03 UTC by oleorhagen

I'm at the point now I would like to discuss how to approach this from now on.

This simple PoC works locally, but has some serious holes in it of course.

We need to figure out:

* How to handle dependencies (like ansible (pip) and ansible ini module) needs to be installed on the target already - what is the normal way of handling this ? :thinking:  For now I've hard-coded the path to the module to my local setup's path, to get it running, but this is not what we want to do of course. Should the meta-data provide the path, or what should we do?

* The default values I'm guessing is not really necessary to handle in the promise module (Ansible knows of them already), and we are not guaranteed they are going to stay in sync.

2024-01-11 08:13 UTC, oleorhagen commented on promise-types/ini/ini.py
> +        self.add_attribute("unsafe_writes", bool, default=False)
Good point :p

However, I'm unsure if we should add these at all, or just pass them through transparently?

2024-01-12 13:52 UTC, oleorhagen commented
For now I've added a `cfbs.json` file in the directory. However, I see all other modules are incorportated into the top-level `cfbs.json`. I'm guessing you want me to follow that example?

2024-01-12 13:55 UTC, olehermanse commented
> For now I've added a `cfbs.json` file in the directory. However, I see all other modules are incorportated into the top-level `cfbs.json`. I'm guessing you want me to follow that example?

@oleorhagen Yea. Either that, or you can also develop the module in your own repo, if you prefer.

2024-01-12 13:59 UTC, olehermanse commented on promise-types/ini/example.cf
> +promise agent ini
@oleorhagen sorry that we don't have a good automatic formatter for policy language (yet). Please take a look at the style guide here and try to align with it (doesn't have to be perfect):

https://docs.cfengine.com/docs/master/examples-tutorials-writing-and-serving-policy-policy-style.html#top

2024-01-15 10:01 UTC, oleorhagen commented on promise-types/ini/ini.py
> +        self.add_attribute("unsafe_writes", bool, default=False)
Ended up just passing them through transparently

2024-01-15 10:01 UTC, oleorhagen commented on promise-types/ini/example.cf
> +promise agent ini
Did my best. See latest push

2024-01-15 10:05 UTC, oleorhagen commented on promise-types/ini/README.md
> +* Python installed on the system (?)
Should I leave this in or not?

2024-01-15 10:31 UTC, oleorhagen commented on promise-types/ini/README.md
> +* Python installed on the system (?)
Left it in and added the `ansible-core` package requirement as well, also removed them from the policy for now, I don't see any of the other promises installing their dependencies. So trying to keep it consistent.

2024-01-16 16:36 UTC, craigcomstock reviewed
cool! thanks for this work!

2024-01-16 16:36 UTC, craigcomstock commented on promise-types/ini/example.cf
> +    "got_ini_file" expression => "$(ansible_ini_file[success])";
I would expect more of a `have_ansible_ini_file_module` class which hinges on the file being present, not the result of `url_get`.

Best to think of the end-state you wish, not the momentary state. e.g. have-ini-file instead of just-got-ini-file-with-url-get-function. Thinking policy is an imperative language here induces madness and frustration. ;) 

Would be kind of cool if we could get `cfbs build` to do some of this prep work, like download ini_file.py into the policy set, maybe with a checksum. :)

2024-01-16 16:36 UTC, craigcomstock commented on promise-types/ini/example.cf
> +      "/tmp/cfe/ini_file.py"
for re-use sake I would say put this in the statedir (typically /var/cfengine/state) and set a var for it.

```suggestion
      "${ansible_ini_file_module_path}"
```

so earlier

```
  vars:
    "ansible_ini_file_module_path" string => "${sys.statedir}/ansible_modules/ini_file.py";
```

see https://docs.cfengine.com/docs/3.21/reference-special-variables-sys.html#sys-statedir

2024-01-16 16:36 UTC, craigcomstock commented on promise-types/ini/ini.py
> +        self.log_debug("Received output: %s (stdout)" % proc.stdout)
right, here, when returncode is 0 you should parse results somehow and provide some info logging about what changed if anything: file created, file modified, ... maybe by changing the options sent to the ansible module.

2024-01-16 18:04 UTC, nickanderson requested changes

2024-01-16 18:04 UTC, nickanderson commented on promise-types/ini/example.cf
> +      module_path => "/tmp/cfe/ini_file.py",
Yeah, I don't think we should have to specify `module_path` on the individual promise. That should be handled by setting up the promise type.

2024-01-16 18:06 UTC, nickanderson commented on promise-types/ini/ini.py
> +        assert meta.get("promise_type") == "ini"
```suggestion
        assert meta.get("promise_type") == "ansible_ini"
```

2024-01-17 01:05 UTC, olehermanse commented on promise-types/ini/README.md
> +* *Description*: Manage TOML configuration files through the Ansible INI module in CFEngine.
@oleorhagen AFAICT TOML and ini are 2 similar but different file formats. Does the Ansible module work for / target both TOML and ini files?

https://en.wikipedia.org/wiki/INI_file

2024-01-17 01:08 UTC, olehermanse commented on promise-types/ini/README.md
> +  ini:
I don't agree. The promise type should refer to what resource we are managing, not how it was implemented (python, ansible, etc.).

`ini` or maybe `ini_files` (similar to `files` promises) are appropriate names here, IMO.

2024-01-17 08:39 UTC, oleorhagen commented on promise-types/ini/README.md
> +* *Description*: Manage TOML configuration files through the Ansible INI module in CFEngine.
hah, lol. TIL. Ur right!

2024-01-17 08:40 UTC, oleorhagen commented on promise-types/ini/README.md
> +* *Description*: Manage TOML configuration files through the Ansible INI module in CFEngine.
Fixing

2024-01-17 08:43 UTC, oleorhagen commented on promise-types/ini/example.cf
> +    "got_ini_file" expression => "$(ansible_ini_file[success])";
Yes, that is much better!

2024-01-17 09:34 UTC, oleorhagen commented on promise-types/ini/ini.py
> +        self.log_debug("Received output: %s (stdout)" % proc.stdout)
Isn't this what is done below in the `try` ? :point_down:

2024-01-17 15:14 UTC, craigcomstock commented on promise-types/ini/ini.py
> +        self.log_debug("Received output: %s (stdout)" % proc.stdout)
I think @olehermanse was trying to mention this. Typically when CFEngine makes a change it logs an INFO message about what it did. I'm not sure your try/catch. I think the message should be more direct and you should build more intelligence into the python code.

It would seem that `changed` key in `d.get("changed")` should log a message like 

```
self.log_info("Ansible INI modified file %s", ...)
```

2024-01-18 08:21 UTC, oleorhagen commented on promise-types/ini/README.md
> +  ini:
I'm sticking to `ini` then I think

2024-01-18 12:04 UTC, olehermanse commented on promise-types/ini/ini.py
> +                self.log_info("Ansible INI returned msg: %s" % d.get("msg", ""))
```suggestion
                self.log_info("Ansible INI returned msg: %s" % d.get("msg", "empty"))
```

2024-01-18 12:06 UTC, olehermanse commented on promise-types/ini/ini.py
> +                self.log_info("Ansible INI returned msg: %s" % d.get("msg", ""))
```
Edited content of 'filename.ini' (msg)
```

2024-02-20 08:51 UTC, oleorhagen commented
@olehermanse feel free to have a last lookover

2024-02-20 16:37 UTC, craigcomstock requested changes
I think we must make the module_path default more dynamic based on platform/host information.

2024-02-20 16:37 UTC, craigcomstock commented on libraries/python/cfengine.py
> +                + e.message
seems like this would read easier and fit in one line.

2024-02-20 16:37 UTC, craigcomstock commented on libraries/python/cfengine.py
> +                + e.message
then again, what does `black` say? yeah, black seems to agree with me. Maybe run all your python files through `black`

2024-02-20 16:37 UTC, craigcomstock commented on promise-types/ini/README.md
> +        value => "baz";
either

```suggestion
        section => "foo",
        option => "bar",
        value => "baz";
```

or

```suggestion
        section => "foo",
        option  => "bar",
        value   => "baz";
```

2024-02-20 16:37 UTC, craigcomstock commented on promise-types/ini/example.cf
> +      value => "baz";
same deal here as in other example, tidy up whitespace either tight (one space between attribute name and fat arrow) or lined up vertically.

2024-02-20 16:37 UTC, craigcomstock commented on promise-types/ini/ini.py
> +"""The ultimate CFEngine custom promise module"""
🏆

2024-02-20 16:37 UTC, craigcomstock commented on promise-types/ini/ini.py
> +        if "module_path" not in attributes:
Related to the TODO above where validation "does not work" here we provide a reasonable default? Doesn't seem like it actually since we are assuming here python3.11 which is a wild assumption for many different platforms.

Can we be smarter here about the path?

I had to `pip3 install ansible` in order to get ini_file.py. `pip3 install ansible-core` didn't do enough.

If I do `pip3 show ansible` I get an idea of where to look that is dependent on the install which might be better and something we can do programmatically via python?

```
? pip3 show ansible
Name: ansible
Version: 9.2.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPL-3.0-or-later
Location: /usr/local/lib/python3.11/site-packages
Requires: ansible-core
Required-by: 
```

2024-02-21 09:49 UTC, oleorhagen commented on libraries/python/cfengine.py
> +                + e.message
Hmm, this is `black`. But I'm guessing it's a version thing then. I used `19`. but don't know what your standard is

2024-02-21 09:57 UTC, oleorhagen commented on promise-types/ini/ini.py
> +        if "module_path" not in attributes:
I get your point, and I agree. However, I won't have time to finish this, and it seems the other modules too write in their `Readme`'s that the prerequisites need to be installed. 

I fiddled around with how to provide this, and tried a few different things:

1. Having the path in the `promise agent ini` setup, but this apparently is not valid syntax
2. Having it in the `meta` section in the promise - but this does not get passed to the custom promise module (only 
3. Hardcoding it as I've done now.

Dynamically would have been the sweetest though

2024-02-21 11:42 UTC, oleorhagen commented on promise-types/ini/ini.py
> +        if "module_path" not in attributes:
> I had to pip3 install ansible in order to get ini_file.py. pip3 install ansible-core didn't do enough.

This is true, if we do not provide the file ourselves (Like in the original implementation where it was downloaded).

we could consider adding the file to the repo, and have it installed just as we do the custom promise module `ini.py` itself?

2024-02-21 14:03 UTC, craigcomstock commented on promise-types/ini/ini.py
> +        if "module_path" not in attributes:
Right on. Two things then: 
- we need to update the requirements to include ansible since that's easier than having folks have to figure out where to get it.
- make the path dynamic with some python code if possible, doesn't have to be done by you :)

2024-02-26 12:05 UTC, olehermanse commented on promise-types/ini/example.cf
> +    "promise_type"   string => "ini";
Using the `meta` promise type won't do anything for the promise module.

You could use the `meta` attribute per promise:

```
  ini:
    "hello.ini"
      meta => { "report", "some=value" };
```

But it seems to me that the information you want to pass is more static, so would fit better if we make some room for it in the `promise agent` block.

2024-02-26 12:07 UTC, olehermanse commented on promise-types/ini/example.cf
> +  interpreter => "/usr/bin/python3";
We could enable setting environment variables for the module, or add another field of "data" to pass to the module here.

2024-02-26 12:10 UTC, oleorhagen commented on promise-types/ini/example.cf
> +  interpreter => "/usr/bin/python3";
Yes, I like the `data` field idea

2026-06-08 20:20 UTC, closed without merging