CFE-4159: Changed to info log level on promise repaired for `groups` promise type
cfengine/modules pull request #89
Opened 2024-01-18 13:30 UTC by larsewi

2024-01-18 15:30 UTC, olehermanse requested changes

2024-01-18 15:30 UTC, olehermanse commented on promise-types/groups/groups.py
> +            self.log_info("Promise '%s' repaired" % promiser)
I don't think this is right. The outcome of the promise fits well in verbose log. What we'd like in the info log is real (human readable) information about what was changed.

I see there is already 1 good log message for this above (`Deleted group '%s'`).

So I'd say keep this one as is, but introduce other info log messages further up / where the changes are actually made.

Some ideas;

```
Added 'larsewi' to 'developers' group
Removed 'larsewi' from 'developers' group
Set members of 'developers' group to be: larsewi, craigcomstock 
```

2024-01-18 17:17 UTC, craigcomstock commented on promise-types/groups/groups.py
> +            self.log_info("Promise '%s' repaired" % promiser)
Agreed, as we were just discussing this in regards to the ini module. :+1:

2024-01-31 15:56 UTC, larsewi commented
Failed to reproduce the error message, even when using the same policy that I used when I logged this ticket. Closing the ticket. Looking through the code, I cannot see any place where the module returns `Result.REPAIRED` without logging a message with log level info.

2024-01-31 15:56 UTC, closed without merging