CFE-3655: ansible promise type for running playbooks
cfengine/modules pull request #9
Opened 2021-06-04 09:28 UTC by tranchitella

2021-06-04 09:28 UTC, tranchitella commented
@olehermanse ping

2021-06-04 10:47 UTC, olehermanse approved these changes
Looks really good, Fabio! I haven't tested it, but here are some smaller suggestions.

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/README.md
> +| `tags` | `slist` | List of tags to play | no | `{}` |
```suggestion
| `tags` | `slist` | List of tags to play | No | `{}` |
```

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/README.md
> +| `remote_user` | `string` | Set the `remote_user` option | - | `root` |
Why do these have ` - ` for Mandatory column while the ones above have `No` ?

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/README.md
> +[CFengine](https://cfengine.com) is sponsored by [Northern.tech AS](https://northern.tech)
```suggestion
[CFEngine](https://cfengine.com) is sponsored by [Northern.tech AS](https://northern.tech)
```

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/ansible_promise.py
> +COMPAT_OPTIONS = (
Maybe a comment to explain what COMPAT_OPTIONS means? Compatibility with what?

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/example.cf
> +      inventory => "/tmp/inventory.yaml",
Maybe you could add a small dummy playbook to make it complete and the example runnable?

2021-06-04 10:47 UTC, olehermanse commented on promise_types/ansible/ansible_promise.py
> +                raise ValidationError(f"must be an absolute path, not '{v}'")
```suggestion
                raise ValidationError(f"Must be an absolute path, not '{v}'")
```

2021-06-04 12:40 UTC, olehermanse commented
@tranchitella your change to cfengine.py was already merged here: https://github.com/cfengine/modules/pull/10

You can rebase and drop that commit :)

2021-06-05 03:33 UTC, tranchitella commented on promise_types/ansible/README.md
> +| `remote_user` | `string` | Set the `remote_user` option | - | `root` |
It's a mistake, I'm fixing it in the other READMEs as well.

2021-06-05 03:38 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +COMPAT_OPTIONS = (
sorry, it was a left-over

2021-06-05 03:41 UTC, tranchitella commented
@olehermanse I addressed your comments, rebased and fixed the other README files.
Can you please review it again and merge, in case it is okay? I don't have merge rights in this repo.
Thanks.

2021-06-08 08:13 UTC, vpodzime requested changes
Please split the changes in the *git* module into a separate commit.

2021-06-08 08:13 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +    from ansible.vars.manager import VariableManager
Please only do the imports in the `try-except` block. The class definition shouldn't be inside it.

2021-06-08 08:13 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
This formatting breaks the flow of the code. I think this would be better:
```
def evaluate_promise(self, safe_promise: str, attributes: Dict)
                                   -> Tuple[str, List[str]]:
```
or even with everything on one line. Nobody's going to print this code on a toilet paper.

2021-06-08 08:13 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +        pbex._tqm._stdout_callback = callback
Is there a way to avoid accessing private attributes?

2021-06-08 09:41 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +    from ansible.vars.manager import VariableManager
The class depends on CallbackBase, which is imported conditionally. This is the reason why the class definition is in the try block. This is a common pattern in Python, I believe.

2021-06-08 09:42 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
The code is automatically formatted using black to avoid formatting bikeshedding.

2021-06-08 09:56 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +        pbex._tqm._stdout_callback = callback
> Please split the changes in the _git_ module into a separate commit.

done

2021-06-08 09:58 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +        pbex._tqm._stdout_callback = callback
> Is there a way to avoid accessing private attributes?

Yes, but it would require bloating the Python code with all the initialization of the task queue manager which the PlaybookExecutor embeds. In any case, _stdout_callback is private, thus we would need to override the TaskQueueManager, adding additional complexity. I don't think it's a good idea, but if you disagree I can give it a try.

2021-06-08 11:08 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +    from ansible.vars.manager import VariableManager
The class can be defined inside an `if ANSIBLE_AVAILABLE`.

2021-06-08 11:09 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +        pbex._tqm._stdout_callback = callback
Not worth the struggle, AFAICT. We just need to hope the names stay the same.

2021-06-08 11:31 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +    from ansible.vars.manager import VariableManager
ok done

2021-06-08 11:32 UTC, tranchitella commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
I'm use black to format my Python code, if the policy in CFEngine is not relying on autoformatter let me know and I'll manually format it according to your policy.

2021-06-08 12:17 UTC, olehermanse commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
@tranchitella black is better ;) Ignore him, your formatting is perfect.

2021-06-08 12:21 UTC, merged

2021-06-08 12:26 UTC, olehermanse commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
@vpodzime The problem is that you end up arguing something extremely subjective. I don't print my code on toilet paper and I still think Fabios snippet here is more readable than your suggestion.

2021-06-09 07:33 UTC, vpodzime commented on promise_types/ansible/ansible_promise.py
> +    ) -> Tuple[str, List[str]]:
OK. If **you guys** prefer such formatting, that's the way to go. But not just because some formatter puts it that way. Formatting preferences differ, for me "everything after `def something` should be indented more than the `def`" is quite a key for readability and flow of the code. But YMMV, of course.