Renamed meta to metadata and other cleanups
cfengine/modules pull request #90
Opened 2024-02-28 16:45 UTC by olehermanse

- Python promise modules: Renamed meta parameter to metadata
- Cleaned up README files relating to the updated promise types
- iptables.py: Autoformatting by black
- Bumped version numbers of to be released modules inside python source code

2024-02-28 16:50 UTC, nickanderson commented on libraries/python/README.md
> +https://docs.cfengine.com/docs/3.21/getting-started.html
```suggestion
https://docs.cfengine.com/latest/getting-started.html
```

Maybe link to latest, lts or docs/master ?

2024-02-28 16:50 UTC, nickanderson commented on libraries/python/README.md
> +https://docs.cfengine.com/docs/3.21/reference-promise-types-custom.html
Same here, maybe link to a not specific version

2024-02-28 16:53 UTC, nickanderson requested changes
Seems pretty ok, just saw one case of markdown formatting used in org formatted document that needs to be fixed. Suggested changing links to not version specific.

2024-02-28 16:53 UTC, nickanderson commented on promise-types/http/README.org
> +The `http` promise type lets you perform HTTP(S) requests from policy.
```suggestion
The =http= promise type lets you perform HTTP(S) requests from policy.
```
This one is org-mode formatted. So you would want to use `=`

2024-02-28 16:58 UTC, olehermanse commented on promise-types/http/README.org
> +The `http` promise type lets you perform HTTP(S) requests from policy.
Fixed, thanks.

2024-02-28 17:16 UTC, nickanderson approved these changes

2024-02-28 17:16 UTC, nickanderson commented on libraries/python/README.md
> +https://docs.cfengine.com/docs/3.21/getting-started.html
yeah i always struggle to decide.

2024-02-28 17:52 UTC, merged

2024-02-29 08:50 UTC, larsewi commented on promise-types/iptables/iptables.py
> +    def evaluate_promise(self, promiser: str, attributes: Dict, metadata: Dict):
What is the reason for using `typing.Dict` instead of `dict`?

2024-02-29 11:37 UTC, olehermanse commented on promise-types/iptables/iptables.py
> +    def evaluate_promise(self, promiser: str, attributes: Dict, metadata: Dict):
I didn't mean anything special by it, I just copy-pasted the function signature from one of the other ones (git promise type I think).

It could make sense to always use the typing ones, make everything look consistent, and they have some more expressive ones. But I don't really have a strong opinion.